spring:
  application:
    name: projet-puericulture

  # Configuration PostgreSQL (Supabase)
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Sécurité : structure immuable en runtime
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Configuration de la sécurité (JWT stateless)
  security:
    jwt:
      token-validity: 86400 # 24 heures

# Configuration de la documentation API (Swagger)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Gestion des logs (Interdiction des try/catch vides)
logging:
  level:
    root: INFO
    org.springframework.security: INFO
    com.projetpuericulture: DEBUG # Debug activé pour le socle et les verticales