spring.application.name=demo
spring.ai.openai.api-key=sk-dummy-key-for-testing
spring.datasource.url=postgresql://postgres:postgres@127.0.0.1:54322/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres