-- 1. Table Users (Extensions de profiles pour Supabase Auth)
CREATE TABLE public.profiles
(
    id         uuid REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    email      TEXT UNIQUE,
    name       TEXT,
    firstname  TEXT,
    city      TEXT,
    street     TEXT
);

-- 2. Table Posts
CREATE TABLE public.posts
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id         uuid REFERENCES public.profiles (id) ON DELETE CASCADE NOT NULL,
    title             TEXT                                                   NOT NULL,
    description       TEXT,
    images_references TEXT, -- Stockage des URLs ou chemins
    open              BOOLEAN                  DEFAULT true,
    created_at        TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);


-- 3. Table SecondHand
CREATE TABLE public.second_hand
(
    id        BIGINT REFERENCES public.posts (id) ON DELETE CASCADE PRIMARY KEY,
    price     BIGINT NOT NULL,
    condition TEXT -- Ex: 'new', 'good', 'used'
);

-- 4. Table Troc
CREATE TABLE public.troc
(
    id              BIGINT REFERENCES public.posts (id) ON DELETE CASCADE PRIMARY KEY,
    estimated_price BIGINT
);

-- 5. Table Leasing
CREATE TABLE public.leasing
(
    id            BIGINT REFERENCES public.posts (id) ON DELETE CASCADE PRIMARY KEY,
    price         BIGINT NOT NULL,
    duration_days INT    NOT NULL
);

-- 6. Table ForwardTrading
CREATE TABLE public.forward_trading
(
    id BIGINT REFERENCES public.posts (id) ON DELETE CASCADE PRIMARY KEY
);