CREATE TABLE timeline_periods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(50),                  -- ex: "standard", "premature"
    label VARCHAR(50) NOT NULL,        -- ex: "0-3 mois"
    week_duration INT NOT NULL,        -- ex: 12
    order_index INT NOT NULL           -- ex: 1
);

-- INSERT DEFAULT 24 MONTHS QUARTER
INSERT INTO timeline_periods (type, label, week_duration, order_index)
VALUES
    ('T1', '0-3 mois', 13, 1),
    ('T2', '4-6 mois', 13, 2),
    ('T3', '7-9 mois', 13, 3),
    ('T4', '10-12 mois', 13, 4),
    ('T5', '13-15 mois', 13, 5),
    ('T6', '16-18 mois', 13, 6),
    ('T7', '19-21 mois', 13, 7),
    ('T8', '22-24 mois', 13, 8);

ALTER TABLE timeline_events
ADD COLUMN article_price NUMERIC(10,2);

ALTER TABLE timeline_events
ADD COLUMN article_tag VARCHAR(50);

ALTER TABLE timeline_events
ADD COLUMN period_id INT;

ALTER TABLE timeline_events
ADD CONSTRAINT fk_events_period
FOREIGN KEY (period_id)
REFERENCES timeline_periods(id);