-- 按类图创建 users 表，对应 User 实体。
CREATE TABLE IF NOT EXISTS public.users
(
    -- 用户主键，对应 User.id。
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 用户邮箱，对应 User.email。
    email TEXT UNIQUE NOT NULL,
    -- 用户姓氏或名称，对应 User.name。
    name TEXT NOT NULL,
    -- 用户名字，对应 User.firstname。
    firstname TEXT NOT NULL,
    -- 用户密码，对应 User.password。
    password TEXT NOT NULL,
    -- 用户城市，对应 User.city。
    city TEXT NOT NULL,
    -- 用户街道，对应 User.Street。
    street TEXT NOT NULL
);

-- 按类图创建 posts 表，对应 Posts 实体。
CREATE TABLE IF NOT EXISTS public.posts
(
    -- 发布内容主键，对应 Posts.id。
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 作者外键，对应 User 1 到 Posts * 的 Author 关系。
    author_id BIGINT REFERENCES public.users (id) ON DELETE CASCADE NOT NULL,
    -- 发布标题，对应 Posts.title。
    title TEXT NOT NULL,
    -- 发布描述，对应 Posts.description。
    description TEXT NOT NULL,
    -- 图片引用字符串，对应 Posts.ImagesReferences。
    images_references TEXT,
    -- 是否开放，对应 Posts.open。
    open BOOLEAN DEFAULT true NOT NULL
);

-- 按类图创建 second_hand 表，对应 SecondHand 实体。
CREATE TABLE IF NOT EXISTS public.second_hand
(
    -- SecondHand 主键，同时也是 Posts 外键，对应 SecondHand.id。
    id BIGINT REFERENCES public.posts (id) ON DELETE CASCADE PRIMARY KEY,
    -- 二手价格，对应 SecondHand.price。
    price BIGINT NOT NULL,
    -- 物品状态，对应 SecondHand.Condition。
    condition TEXT NOT NULL
);

-- 按类图创建 troc 表，对应 Troc 实体。
CREATE TABLE IF NOT EXISTS public.troc
(
    -- Troc 主键，同时也是 Posts 外键，对应 Troc.id。
    id BIGINT REFERENCES public.posts (id) ON DELETE CASCADE PRIMARY KEY,
    -- 估计价值，对应 Troc.estimated price。
    estimated_price BIGINT NOT NULL
);

-- 按类图创建 leasing 表，对应 Leasing 实体。
CREATE TABLE IF NOT EXISTS public.leasing
(
    -- Leasing 主键，同时也是 Posts 外键，对应 Leasing.id。
    id BIGINT REFERENCES public.posts (id) ON DELETE CASCADE PRIMARY KEY,
    -- 租赁价格，对应 Leasing.price。
    price BIGINT NOT NULL,
    -- 租赁天数，对应 Leasing.duration in days。
    duration BIGINT NOT NULL
);

-- 按类图创建 forward_trading 表，对应 ForwardTrading 实体。
CREATE TABLE IF NOT EXISTS public.forward_trading
(
    -- ForwardTrading 主键，同时也是 Posts 外键，对应 ForwardTrading.id。
    id BIGINT REFERENCES public.posts (id) ON DELETE CASCADE PRIMARY KEY
);
